sh scripts/sh/single.sh texinfo
sh scripts/sh/single.sh libxml2
sh scripts/sh/single.sh bash-preexec
sh scripts/sh/single.sh btyacc
sh scripts/sh/single.sh cjson
sh scripts/sh/single.sh cygnative
sh scripts/sh/single.sh cygrunsrv
sh scripts/sh/single.sh doctest
sh scripts/sh/single.sh fmt
sh scripts/sh/single.sh gc
sh scripts/sh/single.sh genromfs
sh scripts/sh/single.sh git-extras
sh scripts/sh/single.sh gradle
sh scripts/sh/single.sh icmake
sh scripts/sh/single.sh iperf
sh scripts/sh/single.sh libatomic_ops
sh scripts/sh/single.sh libblake3
sh scripts/sh/single.sh localepurge
sh scripts/sh/single.sh lzip
sh scripts/sh/single.sh mksh
sh scripts/sh/single.sh mm-common
sh scripts/sh/single.sh nsinstall
sh scripts/sh/single.sh oniguruma
sh scripts/sh/single.sh pax
sh scripts/sh/single.sh perl-Term-Table
sh scripts/sh/single.sh pwgen
sh scripts/sh/single.sh reflex
sh scripts/sh/single.sh ssh-pageant
sh scripts/sh/single.sh ucl
sh scripts/sh/single.sh xorg-util-macros
sh scripts/sh/single.sh cscope
sh scripts/sh/single.sh hexcurse
sh scripts/sh/single.sh icu
sh scripts/sh/single.sh jq
sh scripts/sh/single.sh ncdu
sh scripts/sh/single.sh vifm
sh scripts/sh/single.sh cpio
sh scripts/sh/single.sh dialog
sh scripts/sh/single.sh idutils
sh scripts/sh/single.sh pv
sh scripts/sh/single.sh rlwrap
sh scripts/sh/single.sh aspell
sh scripts/sh/single.sh dosfstools
sh scripts/sh/single.sh libqrencode
sh scripts/sh/single.sh libtre
sh scripts/sh/single.sh neofetch
sh scripts/sh/single.sh nnn
sh scripts/sh/single.sh psmisc
sh scripts/sh/single.sh rpcsvc-proto
sh scripts/sh/single.sh screenfetch
sh scripts/sh/single.sh sgml-common
sh scripts/sh/single.sh shellspec
sh scripts/sh/single.sh tcsh
sh scripts/sh/single.sh yodl
sh scripts/sh/single.sh aspell-de
sh scripts/sh/single.sh aspell-en
sh scripts/sh/single.sh bc
sh scripts/sh/single.sh busybox
sh scripts/sh/single.sh cmatrix
sh scripts/sh/single.sh colormake
sh scripts/sh/single.sh cygutils
sh scripts/sh/single.sh docbook-sgml
sh scripts/sh/single.sh docbook-sgml31
sh scripts/sh/single.sh etc-update
sh scripts/sh/single.sh fcode-utils
sh scripts/sh/single.sh fzy
sh scripts/sh/single.sh gnu-efi
sh scripts/sh/single.sh gnulib-l10n
sh scripts/sh/single.sh joe
sh scripts/sh/single.sh libbobcat
sh scripts/sh/single.sh lua
sh scripts/sh/single.sh rcs
sh scripts/sh/single.sh shutdown
sh scripts/sh/single.sh tree
sh scripts/sh/single.sh unrar
sh scripts/sh/single.sh bisoncpp
sh scripts/sh/single.sh ccache
sh scripts/sh/single.sh cflow
sh scripts/sh/single.sh flexcpp
sh scripts/sh/single.sh luit
sh scripts/sh/single.sh lzo2
sh scripts/sh/single.sh msgpack-c
sh scripts/sh/single.sh protobuf
sh scripts/sh/single.sh upx
sh scripts/sh/single.sh cdecl
sh scripts/sh/single.sh expect
sh scripts/sh/single.sh gengetopt
sh scripts/sh/single.sh lzop
sh scripts/sh/single.sh nawk
sh scripts/sh/single.sh openbsd-netcat
sh scripts/sh/single.sh unzip
sh scripts/sh/single.sh xorriso
sh scripts/sh/single.sh zip
sh scripts/sh/single.sh dejagnu
sh scripts/sh/single.sh docbook-dsssl
sh scripts/sh/single.sh docx2txt
sh scripts/sh/single.sh enscript
sh scripts/sh/single.sh markdown
sh scripts/sh/single.sh perl-Algorithm-Diff
sh scripts/sh/single.sh perl-Archive-Zip
sh scripts/sh/single.sh perl-Benchmark-Timer
sh scripts/sh/single.sh perl-Capture-Tiny
sh scripts/sh/single.sh perl-Carp-Clan
sh scripts/sh/single.sh perl-common-sense
sh scripts/sh/single.sh perl-Compress-Bzip2
sh scripts/sh/single.sh perl-Data-Munge
sh scripts/sh/single.sh perl-Date-Calc
sh scripts/sh/single.sh perl-DBI
sh scripts/sh/single.sh perl-Digest-HMAC
sh scripts/sh/single.sh perl-Encode-compat
sh scripts/sh/single.sh perl-Exporter-Lite
sh scripts/sh/single.sh perl-Exporter-Tiny
sh scripts/sh/single.sh perl-ExtUtils-Depends
sh scripts/sh/single.sh perl-ExtUtils-MakeMaker
sh scripts/sh/single.sh perl-ExtUtils-PkgConfig
sh scripts/sh/single.sh perl-FFI-CheckLib
sh scripts/sh/single.sh perl-File-chdir
sh scripts/sh/single.sh perl-File-Copy-Recursive
sh scripts/sh/single.sh perl-File-Next
sh scripts/sh/single.sh perl-Getopt-ArgvFile
sh scripts/sh/single.sh perl-Getopt-Tabular
sh scripts/sh/single.sh perl-Importer
sh scripts/sh/single.sh perl-IPC-Run3
sh scripts/sh/single.sh perl-List-MoreUtils-XS
sh scripts/sh/single.sh perl-Math-Int64
sh scripts/sh/single.sh perl-Module-Pluggable
sh scripts/sh/single.sh perl-Mozilla-CA
sh scripts/sh/single.sh perl-Net-IP
sh scripts/sh/single.sh perl-Params-Util
sh scripts/sh/single.sh perl-Path-Class
sh scripts/sh/single.sh perl-Path-Tiny
sh scripts/sh/single.sh perl-PerlIO-gzip
sh scripts/sh/single.sh perl-Probe-Perl
sh scripts/sh/single.sh perl-Regexp-Common
sh scripts/sh/single.sh perl-Role-Tiny
sh scripts/sh/single.sh perl-Scope-Guard
sh scripts/sh/single.sh perl-Socket6
sh scripts/sh/single.sh perl-Spiffy
sh scripts/sh/single.sh perl-Sub-Exporter-Progressive
sh scripts/sh/single.sh perl-Sub-Install
sh scripts/sh/single.sh perl-Test-Needs
sh scripts/sh/single.sh perl-Test-NoWarnings
sh scripts/sh/single.sh perl-Test-Requires
sh scripts/sh/single.sh perl-Test-RequiresInternet
sh scripts/sh/single.sh perl-Test-Warnings
sh scripts/sh/single.sh perl-XML-NamespaceSupport
sh scripts/sh/single.sh perl-XML-SAX-Base
sh scripts/sh/single.sh stow
sh scripts/sh/single.sh swig
sh scripts/sh/single.sh wcd
sh scripts/sh/single.sh zsh
sh scripts/sh/single.sh ack
sh scripts/sh/single.sh lcov
sh scripts/sh/single.sh perl-Data-OptList
sh scripts/sh/single.sh perl-IO-Socket-INET6
sh scripts/sh/single.sh perl-List-MoreUtils
sh scripts/sh/single.sh perl-Net-DNS
sh scripts/sh/single.sh perl-PadWalker
sh scripts/sh/single.sh perl-Return-MultiLevel
sh scripts/sh/single.sh perl-Sub-Info
sh scripts/sh/single.sh perl-Test-Deep
sh scripts/sh/single.sh perl-Test-Fatal
sh scripts/sh/single.sh perl-Test-Script
sh scripts/sh/single.sh perl-Text-Diff
sh scripts/sh/single.sh perl-XML-SAX
sh scripts/sh/single.sh perl-Class-Method-Modifiers
sh scripts/sh/single.sh perl-File-Which
sh scripts/sh/single.sh perl-Module-Runtime
sh scripts/sh/single.sh perl-Sub-Exporter
sh scripts/sh/single.sh perl-Sub-Quote
sh scripts/sh/single.sh perl-TAP-Harness-Archive
sh scripts/sh/single.sh perl-Test-Base
sh scripts/sh/single.sh perl-Test-Exit
sh scripts/sh/single.sh perl-Test2-Suite
sh scripts/sh/single.sh quilt
sh scripts/sh/single.sh txt2html
sh scripts/sh/single.sh p7zip
sh scripts/sh/single.sh perl-Alien-Build
sh scripts/sh/single.sh perl-Devel-GlobalDestruction
sh scripts/sh/single.sh perl-Import-Into
sh scripts/sh/single.sh perl-Test-YAML
sh scripts/sh/single.sh perl-XML-Simple
sh scripts/sh/single.sh sharutils
sh scripts/sh/single.sh axel
sh scripts/sh/single.sh global
sh scripts/sh/single.sh guile
sh scripts/sh/single.sh iperf3
sh scripts/sh/single.sh libidn
sh scripts/sh/single.sh libpcap
sh scripts/sh/single.sh libpipeline
sh scripts/sh/single.sh libwebsockets
sh scripts/sh/single.sh mingw-w64-cross-gcc
sh scripts/sh/single.sh mingw-w64-cross-mingwarm64-gcc
sh scripts/sh/single.sh perl-alien-build-plugin-download-gitlab
sh scripts/sh/single.sh perl-Moo
sh scripts/sh/single.sh socat
sh scripts/sh/single.sh squashfs-tools
sh scripts/sh/single.sh w3m
sh scripts/sh/single.sh whois
sh scripts/sh/single.sh xdelta3
sh scripts/sh/single.sh atool
sh scripts/sh/single.sh lynx
sh scripts/sh/single.sh man-db
sh scripts/sh/single.sh mingw-w64-cross-mingwarm64-tools
sh scripts/sh/single.sh mingw-w64-cross-mingwarm64-winstorecompat
sh scripts/sh/single.sh mingw-w64-cross-tools
sh scripts/sh/single.sh mingw-w64-cross-winstorecompat
sh scripts/sh/single.sh nyacc
sh scripts/sh/single.sh perl-Parallel-ForkManager
sh scripts/sh/single.sh tmux
sh scripts/sh/single.sh winpty
sh scripts/sh/single.sh apr
sh scripts/sh/single.sh cloc
sh scripts/sh/single.sh efitools
sh scripts/sh/single.sh git-flow
sh scripts/sh/single.sh libmicrohttpd
sh scripts/sh/single.sh man-pages-posix
sh scripts/sh/single.sh man2html
sh scripts/sh/single.sh nano-syntax-highlighting
sh scripts/sh/single.sh perl-LWP-Protocol-https
sh scripts/sh/single.sh task
sh scripts/sh/single.sh apr-util
sh scripts/sh/single.sh gdb
sh scripts/sh/single.sh git-filter-repo
sh scripts/sh/single.sh gtest
sh scripts/sh/single.sh libinih
sh scripts/sh/single.sh libssh
sh scripts/sh/single.sh setconf
sh scripts/sh/single.sh cgdb
sh scripts/sh/single.sh cvs
sh scripts/sh/single.sh libtirpc
sh scripts/sh/single.sh tmate
sh scripts/sh/single.sh asciidoctor
sh scripts/sh/single.sh autogen
sh scripts/sh/single.sh ctags
sh scripts/sh/single.sh docbook-mathml
sh scripts/sh/single.sh mosh
sh scripts/sh/single.sh perl-Alien-Libxml2
sh scripts/sh/single.sh python-pyparsing
sh scripts/sh/single.sh sshpass
sh scripts/sh/single.sh docbook-xsl-ns
sh scripts/sh/single.sh editorconfig-vim
sh scripts/sh/single.sh mingw-w64-cross-compiler-rt
sh scripts/sh/single.sh perl-XML-LibXML
sh scripts/sh/single.sh vimpager
sh scripts/sh/single.sh moreutils
sh scripts/sh/single.sh mosquitto
sh scripts/sh/single.sh python-appdirs
sh scripts/sh/single.sh python-babel
sh scripts/sh/single.sh python-beaker
sh scripts/sh/single.sh python-brotli
sh scripts/sh/single.sh python-certifi
sh scripts/sh/single.sh python-charset-normalizer
sh scripts/sh/single.sh python-configobj
sh scripts/sh/single.sh python-fastimport
sh scripts/sh/single.sh python-idna
sh scripts/sh/single.sh python-imagesize
sh scripts/sh/single.sh python-markdown
sh scripts/sh/single.sh python-markupsafe
sh scripts/sh/single.sh python-merge3
sh scripts/sh/single.sh python-more-itertools
sh scripts/sh/single.sh python-pip
sh scripts/sh/single.sh python-poetry-core
sh scripts/sh/single.sh python-py3c
sh scripts/sh/single.sh python-pycparser
sh scripts/sh/single.sh python-resolvelib
sh scripts/sh/single.sh python-roman-numerals
sh scripts/sh/single.sh python-semantic-version
sh scripts/sh/single.sh python-setuptools-gettext
sh scripts/sh/single.sh python-six
sh scripts/sh/single.sh python-smartypants
sh scripts/sh/single.sh python-snowballstemmer
sh scripts/sh/single.sh python-sphinx-alabaster-theme
sh scripts/sh/single.sh python-sphinxcontrib-applehelp
sh scripts/sh/single.sh python-sphinxcontrib-devhelp
sh scripts/sh/single.sh python-sphinxcontrib-htmlhelp
sh scripts/sh/single.sh python-sphinxcontrib-jsmath
sh scripts/sh/single.sh python-sphinxcontrib-qthelp
sh scripts/sh/single.sh python-sphinxcontrib-serializinghtml
sh scripts/sh/single.sh python-zstandard
sh scripts/sh/single.sh scons
sh scripts/sh/single.sh txt2tags
sh scripts/sh/single.sh colordiff
sh scripts/sh/single.sh crosstool-ng
sh scripts/sh/single.sh elinks
sh scripts/sh/single.sh grml-zsh-config
sh scripts/sh/single.sh guile-mqtt
sh scripts/sh/single.sh gyp
sh scripts/sh/single.sh opensp
sh scripts/sh/single.sh patchutils
sh scripts/sh/single.sh python-cffi
sh scripts/sh/single.sh python-jinja
sh scripts/sh/single.sh python-mako
sh scripts/sh/single.sh python-pacdb
sh scripts/sh/single.sh python-pkgconfig
sh scripts/sh/single.sh python-yaml
sh scripts/sh/single.sh remake
sh scripts/sh/single.sh serf
sh scripts/sh/single.sh tig
sh scripts/sh/single.sh yasm
sh scripts/sh/single.sh cyrus-sasl
sh scripts/sh/single.sh dtc
sh scripts/sh/single.sh irssi
sh scripts/sh/single.sh lftp
sh scripts/sh/single.sh mercurial
sh scripts/sh/single.sh neon
sh scripts/sh/single.sh tio
sh scripts/sh/single.sh mc
sh scripts/sh/single.sh subversion
sh scripts/sh/single.sh u-boot-tools
sh scripts/sh/single.sh znc
sh scripts/sh/single.sh python-colorama
sh scripts/sh/single.sh python-hatch-fancy-pypi-readme
sh scripts/sh/single.sh python-hatch-vcs
sh scripts/sh/single.sh python-typogrify
sh scripts/sh/single.sh python-wcwidth
sh scripts/sh/single.sh rust
sh scripts/sh/single.sh cargo-c
sh scripts/sh/single.sh cargo-edit
sh scripts/sh/single.sh gi-docgen
sh scripts/sh/single.sh git-crypt
sh scripts/sh/single.sh just
sh scripts/sh/single.sh pass
sh scripts/sh/single.sh python-attrs
sh scripts/sh/single.sh python-iniconfig
sh scripts/sh/single.sh python-setuptools-rust
sh scripts/sh/single.sh python-urllib3
sh scripts/sh/single.sh uutils-coreutils
sh scripts/sh/single.sh maturin
sh scripts/sh/single.sh mutt
sh scripts/sh/single.sh neomutt
sh scripts/sh/single.sh python-dulwich
sh scripts/sh/single.sh python-fastbencode
sh scripts/sh/single.sh python-patiencediff
sh scripts/sh/single.sh python-pytest
sh scripts/sh/single.sh python-requests
sh scripts/sh/single.sh breezy
sh scripts/sh/single.sh pactoys
sh scripts/sh/single.sh pacutils
sh scripts/sh/single.sh pkgfile
sh scripts/sh/single.sh python-cryptography
sh scripts/sh/single.sh python-pyalpm
sh scripts/sh/single.sh python-sphinx
sh scripts/sh/single.sh uv
sh scripts/sh/single.sh ansible-core
sh scripts/sh/single.sh fish
sh scripts/sh/single.sh namcap
sh scripts/sh/single.sh ansible
sh scripts/sh/single.sh fisher
