#!/bin/bash
sh build-single.sh gcc
MSYS_BUILD_PKGSUMS=enabled MSYS_BOOTSTRAP_RUST=enabled sh build-single.sh rust
sh build-single.sh texinfo
sh build-single.sh btyacc
sh build-single.sh cygnative
sh build-single.sh cygrunsrv
sh build-single.sh dosfstools
sh build-single.sh gc
sh build-single.sh genromfs
sh build-single.sh git-extras
sh build-single.sh gradle
sh build-single.sh icmake
sh build-single.sh iperf
sh build-single.sh libatomic_ops
sh build-single.sh libqrencode
sh build-single.sh libyaml
sh build-single.sh localepurge
sh build-single.sh lzip
sh build-single.sh mksh
sh build-single.sh nsinstall
sh build-single.sh oniguruma
sh build-single.sh pax
sh build-single.sh perl-Term-Table
sh build-single.sh pwgen
sh build-single.sh reflex
sh build-single.sh ssh-pageant
sh build-single.sh ucl
sh build-single.sh xorg-util-macros
sh build-single.sh icu
sh build-single.sh jq
sh build-single.sh man-pages-posix
sh build-single.sh setconf
sh build-single.sh sgml-common
sh build-single.sh apr
sh build-single.sh cscope
sh build-single.sh docbook-sgml
sh build-single.sh docbook-sgml31
sh build-single.sh hexcurse
sh build-single.sh ncdu
sh build-single.sh rcs
sh build-single.sh tcsh
sh build-single.sh vifm
sh build-single.sh lzo2
sh build-single.sh aspell
sh build-single.sh bc
sh build-single.sh cpio
sh build-single.sh dialog
sh build-single.sh idutils
sh build-single.sh libtre
sh build-single.sh popt
sh build-single.sh psmisc
sh build-single.sh pv
sh build-single.sh rlwrap
sh build-single.sh rpcsvc-proto
sh build-single.sh aspell-de
sh build-single.sh etc-update
sh build-single.sh lzop
sh build-single.sh neofetch
sh build-single.sh screenfetch
sh build-single.sh shellspec
sh build-single.sh yodl
sh build-single.sh aspell-en
sh build-single.sh busybox
sh build-single.sh cmatrix
sh build-single.sh colormake
sh build-single.sh cygutils
sh build-single.sh fcode-utils
sh build-single.sh fzy
sh build-single.sh gnulib-l10n
sh build-single.sh joe
sh build-single.sh libbobcat
sh build-single.sh lua
sh build-single.sh shutdown
sh build-single.sh tree
sh build-single.sh unrar
sh build-single.sh unzip
sh build-single.sh zip
sh build-single.sh cflow
sh build-single.sh bisoncpp
sh build-single.sh cdecl
sh build-single.sh flexcpp
sh build-single.sh gengetopt
sh build-single.sh luit
sh build-single.sh nawk
sh build-single.sh protobuf
sh build-single.sh xorriso
sh build-single.sh docbook-dsssl
sh build-single.sh docx2txt
sh build-single.sh enscript
sh build-single.sh expect
sh build-single.sh markdown
sh build-single.sh perl-Algorithm-Diff
sh build-single.sh perl-Archive-Zip
sh build-single.sh perl-Benchmark-Timer
sh build-single.sh perl-Capture-Tiny
sh build-single.sh perl-Carp-Clan
sh build-single.sh perl-common-sense
sh build-single.sh perl-Data-Munge
sh build-single.sh perl-Date-Calc
sh build-single.sh perl-Digest-HMAC
sh build-single.sh perl-Encode-compat
sh build-single.sh perl-Exporter-Lite
sh build-single.sh perl-Exporter-Tiny
sh build-single.sh perl-ExtUtils-Depends
sh build-single.sh perl-ExtUtils-MakeMaker
sh build-single.sh perl-ExtUtils-PkgConfig
sh build-single.sh perl-FFI-CheckLib
sh build-single.sh perl-File-chdir
sh build-single.sh perl-File-Copy-Recursive
sh build-single.sh perl-File-Next
sh build-single.sh perl-Getopt-ArgvFile
sh build-single.sh perl-Getopt-Tabular
sh build-single.sh perl-Importer
sh build-single.sh perl-IO-Stringy
sh build-single.sh perl-IPC-Run3
sh build-single.sh perl-Module-Pluggable
sh build-single.sh perl-Mozilla-CA
sh build-single.sh perl-Net-IP
sh build-single.sh perl-Path-Class
sh build-single.sh perl-Path-Tiny
sh build-single.sh perl-Probe-Perl
sh build-single.sh perl-Regexp-Common
sh build-single.sh perl-Role-Tiny
sh build-single.sh perl-Scope-Guard
sh build-single.sh perl-Spiffy
sh build-single.sh perl-Sub-Exporter-Progressive
sh build-single.sh perl-Sub-Install
sh build-single.sh perl-Test-Needs
sh build-single.sh perl-Test-NoWarnings
sh build-single.sh perl-Test-Requires
sh build-single.sh perl-Test-Requiresinternet
sh build-single.sh perl-Test-Warnings
sh build-single.sh perl-XML-NamespaceSupport
sh build-single.sh perl-XML-SAX-Base
sh build-single.sh stow
sh build-single.sh wcd
sh build-single.sh ack
sh build-single.sh dejagnu
sh build-single.sh perl-Compress-Bzip2
sh build-single.sh perl-DBI
sh build-single.sh perl-List-MoreUtils-XS
sh build-single.sh perl-Math-Int64
sh build-single.sh perl-Net-DNS
sh build-single.sh perl-PadWalker
sh build-single.sh perl-Params-Util
sh build-single.sh perl-PerlIO-gzip
sh build-single.sh perl-Return-MultiLevel
sh build-single.sh perl-Socket6
sh build-single.sh perl-Sub-Info
sh build-single.sh perl-Test-Deep
sh build-single.sh perl-Test-Fatal
sh build-single.sh perl-Test-Script
sh build-single.sh perl-Text-Diff
sh build-single.sh perl-XML-SAX
sh build-single.sh apr-util
sh build-single.sh lcov
sh build-single.sh perl-Class-Method-Modifiers
sh build-single.sh perl-Data-OptList
sh build-single.sh perl-File-Which
sh build-single.sh perl-IO-Socket-INET6
sh build-single.sh perl-List-MoreUtils
sh build-single.sh perl-Module-Runtime
sh build-single.sh perl-Sub-Quote
sh build-single.sh perl-TAP-Harness-Archive
sh build-single.sh perl-Test-Base
sh build-single.sh perl-Test-Exit
sh build-single.sh perl-Test2-Suite
sh build-single.sh perl-XML-Simple
sh build-single.sh swig
sh build-single.sh txt2html
sh build-single.sh zsh
sh build-single.sh p7zip
sh build-single.sh perl-Alien-Build
sh build-single.sh perl-Import-Into
sh build-single.sh perl-Sub-Exporter
sh build-single.sh perl-Test-YAML
sh build-single.sh git-flow
sh build-single.sh perl-alien-build-plugin-download-gitlab
sh build-single.sh perl-Devel-GlobalDestruction
sh build-single.sh quilt
sh build-single.sh axel
sh build-single.sh iperf3
sh build-single.sh libpipeline
sh build-single.sh perl-Moo
sh build-single.sh socat
sh build-single.sh w3m
sh build-single.sh perl-Parallel-ForkManager
sh build-single.sh sharutils
sh build-single.sh squashfs-tools
sh build-single.sh cloc
sh build-single.sh git-filter-repo
sh build-single.sh gtest
sh build-single.sh libidn
sh build-single.sh man-db
sh build-single.sh perl-LWP-Protocol-https
sh build-single.sh tmux
sh build-single.sh atool
sh build-single.sh man2html
sh build-single.sh whois
sh build-single.sh cvs
sh build-single.sh doctest
sh build-single.sh fmt
sh build-single.sh global
sh build-single.sh libblake3
sh build-single.sh libpcap
sh build-single.sh libssh
sh build-single.sh libtirpc
sh build-single.sh lynx
sh build-single.sh msgpack-c
sh build-single.sh nano-syntax-highlighting
sh build-single.sh python-pyparsing
sh build-single.sh upx
sh build-single.sh ruby
sh build-single.sh tmate
sh build-single.sh docbook-mathml
sh build-single.sh python-appdirs
sh build-single.sh python-babel
sh build-single.sh python-beaker
sh build-single.sh python-brotli
sh build-single.sh python-certifi
sh build-single.sh python-charset-normalizer
sh build-single.sh python-configobj
sh build-single.sh python-fastimport
sh build-single.sh python-idna
sh build-single.sh python-imagesize
sh build-single.sh python-markdown
sh build-single.sh python-markupsafe
sh build-single.sh python-more-itertools
sh build-single.sh python-patiencediff
sh build-single.sh python-pip
sh build-single.sh python-poetry-core
sh build-single.sh python-py3c
sh build-single.sh python-pycparser
sh build-single.sh python-resolvelib
sh build-single.sh python-roman-numerals
sh build-single.sh python-semantic-version
sh build-single.sh python-six
sh build-single.sh python-smartypants
sh build-single.sh python-snowballstemmer
sh build-single.sh python-sphinx-alabaster-theme
sh build-single.sh python-sphinxcontrib-applehelp
sh build-single.sh python-sphinxcontrib-devhelp
sh build-single.sh python-sphinxcontrib-htmlhelp
sh build-single.sh python-sphinxcontrib-jsmath
sh build-single.sh python-sphinxcontrib-qthelp
sh build-single.sh python-sphinxcontrib-serializinghtml
sh build-single.sh python-wcwidth
sh build-single.sh python-zstandard
sh build-single.sh scons
sh build-single.sh txt2tags
sh build-single.sh vim
sh build-single.sh xdelta3
sh build-single.sh ctags
sh build-single.sh editorconfig-vim
sh build-single.sh grml-zsh-config
sh build-single.sh gyp
sh build-single.sh mm-common
sh build-single.sh python-cffi
sh build-single.sh python-jinja
sh build-single.sh python-mako
sh build-single.sh python-pacdb
sh build-single.sh python-yaml
sh build-single.sh serf
sh build-single.sh vimpager
sh build-single.sh ccache
sh build-single.sh docbook-xsl-ns
sh build-single.sh dtc
sh build-single.sh guile
sh build-single.sh libinih
sh build-single.sh mercurial
sh build-single.sh nnn
sh build-single.sh openbsd-netcat
sh build-single.sh perl-Alien-Libxml2
sh build-single.sh python-pkgconfig
sh build-single.sh cyrus-sasl
sh build-single.sh mingw-w64-cross-gcc
sh build-single.sh mingw-w64-cross-mingwarm64-gcc
sh build-single.sh moreutils
sh build-single.sh mosh
sh build-single.sh mosquitto
sh build-single.sh perl-XML-LibXML
sh build-single.sh sshpass
sh build-single.sh autogen
sh build-single.sh colordiff
sh build-single.sh gdb
sh build-single.sh mingw-w64-cross-mingwarm64-tools
sh build-single.sh mingw-w64-cross-mingwarm64-winstorecompat
sh build-single.sh nyacc
sh build-single.sh opensp
sh build-single.sh patchutils
sh build-single.sh python-colorama
sh build-single.sh python-hatch-fancy-pypi-readme
sh build-single.sh python-hatch-vcs
sh build-single.sh python-typogrify
sh build-single.sh tig
sh build-single.sh tio
sh build-single.sh winpty
sh build-single.sh yasm
sh build-single.sh cgdb
sh build-single.sh gi-docgen
sh build-single.sh guile-mqtt
sh build-single.sh mingw-w64-cross-compiler-rt
sh build-single.sh mingw-w64-cross-tools
sh build-single.sh mingw-w64-cross-winstorecompat
sh build-single.sh neon
sh build-single.sh python-attrs
sh build-single.sh python-iniconfig
sh build-single.sh python-urllib3
sh build-single.sh subversion
sh build-single.sh znc
sh build-single.sh elinks
sh build-single.sh lftp
sh build-single.sh python-pytest
sh build-single.sh python-requests
sh build-single.sh task
sh build-single.sh u-boot-tools
sh build-single.sh crosstool-ng
sh build-single.sh irssi
sh build-single.sh mc
sh build-single.sh python-sphinx
sh build-single.sh remake
sh build-single.sh rust
sh build-single.sh cargo-c
sh build-single.sh cargo-edit
sh build-single.sh fish
sh build-single.sh git-crypt
sh build-single.sh just
sh build-single.sh pass
sh build-single.sh python-setuptools-rust
sh build-single.sh uutils-coreutils
sh build-single.sh fisher
sh build-single.sh maturin
sh build-single.sh python-dulwich
sh build-single.sh python-fastbencode
sh build-single.sh breezy
sh build-single.sh mutt
sh build-single.sh neomutt
sh build-single.sh pactoys
sh build-single.sh pacutils
sh build-single.sh pkgfile
sh build-single.sh python-cryptography
sh build-single.sh python-pyalpm
sh build-single.sh uv
sh build-single.sh ansible-core
sh build-single.sh namcap
sh build-single.sh ansible
