sh build-single.sh autoconf-archive
sh build-single.sh brotli
sh build-single.sh c-ares
sh build-single.sh diffstat
sh build-single.sh expat
sh build-single.sh filesystem
sh build-single.sh gmp
sh build-single.sh groff
sh build-single.sh jansson
sh build-single.sh libargp
sh build-single.sh libcbor
sh build-single.sh libffi
sh build-single.sh libuv
sh build-single.sh libxcrypt
sh build-single.sh libyaml
sh build-single.sh mingw-w64-cross-headers
sh build-single.sh mingw-w64-cross-mingwarm64-headers
sh build-single.sh mpdecimal
sh build-single.sh msys2-keyring
sh build-single.sh ncurses
sh build-single.sh nghttp3
sh build-single.sh npth
sh build-single.sh pacman-mirrors
sh build-single.sh pkgconf
sh build-single.sh publicsuffix-list
sh build-single.sh time
sh build-single.sh windows-default-manifest
sh build-single.sh xorgproto
sh build-single.sh xxhash
sh build-single.sh zstd
sh build-single.sh cocom
sh build-single.sh getent
sh build-single.sh gettext
sh build-single.sh isl
sh build-single.sh jsoncpp
sh build-single.sh lndir
sh build-single.sh mpfr
sh build-single.sh nettle
sh build-single.sh readline
sh build-single.sh bash
sh build-single.sh cppdap
sh build-single.sh help2man
sh build-single.sh libiconv
sh build-single.sh mpc
sh build-single.sh procps-ng
sh build-single.sh tftp-hpa
sh build-single.sh bash-completion
sh build-single.sh coreutils
sh build-single.sh db
sh build-single.sh diffutils
sh build-single.sh ed
sh build-single.sh findutils
sh build-single.sh gawk
sh build-single.sh gdbm
sh build-single.sh inetutils
sh build-single.sh libedit
sh build-single.sh libgpg-error
sh build-single.sh libunistring
sh build-single.sh m4
sh build-single.sh make
sh build-single.sh mintty
sh build-single.sh sed
sh build-single.sh tar
sh build-single.sh which
sh build-single.sh flex
sh build-single.sh libassuan
sh build-single.sh libgcrypt
sh build-single.sh libksba
sh build-single.sh libmd
sh build-single.sh libtool
sh build-single.sh lz4
sh build-single.sh patch
sh build-single.sh tzcode
sh build-single.sh zlib
sh build-single.sh autotools
sh build-single.sh binutils
sh build-single.sh bison
sh build-single.sh bzip2
sh build-single.sh libbsd
sh build-single.sh mingw-w64-cross-binutils
sh build-single.sh pinentry
sh build-single.sh tcl
sh build-single.sh mingw-w64-cross-crt
sh build-single.sh mingw-w64-cross-mingwarm64-binutils
sh build-single.sh mingw-w64-cross-windows-default-manifest
sh build-single.sh pcre
sh build-single.sh pcre2
sh build-single.sh perl
sh build-single.sh sqlite
sh build-single.sh autoconf2.13
sh build-single.sh autoconf2.69
sh build-single.sh autoconf2.71
sh build-single.sh autoconf2.72
sh build-single.sh automake1.11
sh build-single.sh automake1.12
sh build-single.sh automake1.13
sh build-single.sh automake1.14
sh build-single.sh automake1.15
sh build-single.sh automake1.16
sh build-single.sh dos2unix
sh build-single.sh less
sh build-single.sh mingw-w64-cross-mingwarm64-crt
sh build-single.sh mingw-w64-cross-mingwarm64-windows-default-manifest
sh build-single.sh mingw-w64-cross-winpthreads
sh build-single.sh perl-Authen-SASL
sh build-single.sh perl-Clone
sh build-single.sh perl-Convert-BinHex
sh build-single.sh perl-Encode-Locale
sh build-single.sh perl-Error
sh build-single.sh perl-ExtUtils-Config
sh build-single.sh perl-ExtUtils-Helpers
sh build-single.sh perl-HTML-Tagset
sh build-single.sh perl-HTTP-Date
sh build-single.sh perl-inc-latest
sh build-single.sh perl-IO-HTML
sh build-single.sh perl-IO-String
sh build-single.sh perl-IO-Stringy
sh build-single.sh perl-JSON
sh build-single.sh perl-Locale-Gettext
sh build-single.sh perl-LWP-MediaTypes
sh build-single.sh perl-MIME-Charset
sh build-single.sh perl-Net-HTTP
sh build-single.sh perl-Pod-Parser
sh build-single.sh perl-sgmls
sh build-single.sh perl-Sort-Versions
sh build-single.sh perl-TermReadKey
sh build-single.sh perl-Text-CharWidth
sh build-single.sh perl-TimeDate
sh build-single.sh perl-Try-Tiny
sh build-single.sh perl-URI
sh build-single.sh perl-XML-Parser
sh build-single.sh perl-YAML-Syck
sh build-single.sh perl-YAML-Tiny
sh build-single.sh util-linux
sh build-single.sh gzip
sh build-single.sh intltool
sh build-single.sh mingw-w64-cross-mingwarm64-winpthreads
sh build-single.sh perl-ExtUtils-InstallPaths
sh build-single.sh perl-File-Listing
sh build-single.sh perl-Font-TTF
sh build-single.sh perl-http-cookiejar
sh build-single.sh perl-HTTP-Message
sh build-single.sh perl-MailTools
sh build-single.sh perl-Module-Build
sh build-single.sh perl-Text-WrapI18N
sh build-single.sh perl-Unicode-LineBreak
sh build-single.sh perl-WWW-RobotRules
sh build-single.sh nasm
sh build-single.sh perl-HTML-Parser
sh build-single.sh perl-HTTP-Cookies
sh build-single.sh perl-HTTP-Negotiate
sh build-single.sh perl-MIME-tools
sh build-single.sh perl-Module-Build-Tiny
sh build-single.sh perl-Test-Pod
sh build-single.sh po4a
sh build-single.sh texinfo
sh build-single.sh automake1.17
sh build-single.sh automake1.18
sh build-single.sh gperf
sh build-single.sh grep
sh build-single.sh libidn2
sh build-single.sh libtasn1
sh build-single.sh openssl
sh build-single.sh perl-HTTP-Daemon
sh build-single.sh xz
sh build-single.sh autotools-wrappers
sh build-single.sh dash
sh build-single.sh libevent
sh build-single.sh libfido2
sh build-single.sh ngtcp2
sh build-single.sh p11-kit
sh build-single.sh perl-libwww
sh build-single.sh perl-Net-SSLeay
sh build-single.sh python
sh build-single.sh rhash
sh build-single.sh rsync
sh build-single.sh doxygen
sh build-single.sh file
sh build-single.sh gnutls
sh build-single.sh heimdal
sh build-single.sh llvm
sh build-single.sh mingw-w64-cross-zlib
sh build-single.sh msys2-launcher
sh build-single.sh msys2-w32api-headers
sh build-single.sh nghttp2
sh build-single.sh perl-IO-Socket-SSL
sh build-single.sh python-flit-core
sh build-single.sh python-setuptools
sh build-single.sh re2c
sh build-single.sh rebase
sh build-single.sh libxml2
sh build-single.sh msys2-w32api-runtime
sh build-single.sh nano
sh build-single.sh openssh
sh build-single.sh perl-Net-SMTP-SSL
sh build-single.sh python-installer
sh build-single.sh ruby
sh build-single.sh docbook-xml
sh build-single.sh libarchive
sh build-single.sh libxslt
sh build-single.sh python-packaging
sh build-single.sh python-pyproject-hooks
sh build-single.sh vim
sh build-single.sh docbook-xsl
sh build-single.sh libpsl
sh build-single.sh ninja
sh build-single.sh python-build
sh build-single.sh asciidoc
sh build-single.sh cython
sh build-single.sh meson
sh build-single.sh python-calver
sh build-single.sh python-docutils
sh build-single.sh python-editables
sh build-single.sh python-mallard-ducktype
sh build-single.sh python-pathspec
sh build-single.sh python-typing_extensions
sh build-single.sh wget
sh build-single.sh xmlto
sh build-single.sh ca-certificates
sh build-single.sh glib2
sh build-single.sh msys2-runtime
sh build-single.sh python-lxml
sh build-single.sh python-setuptools-scm
sh build-single.sh python-trove-classifiers
sh build-single.sh emacs
sh build-single.sh gcc
sh build-single.sh itstool
sh build-single.sh libssh2
sh build-single.sh python-pluggy
sh build-single.sh curl
sh build-single.sh libgit2
sh build-single.sh python-hatchling
sh build-single.sh yelp-xsl
sh build-single.sh cmake
sh build-single.sh gnupg
sh build-single.sh python-pygments
sh build-single.sh yelp-tools
sh build-single.sh git
sh build-single.sh gpgme
sh build-single.sh gtk-doc
sh build-single.sh pacman
sh build-single.sh pacman-contrib
sh build-single.sh base
sh build-single.sh base-devel
